# Dockerfile
FROM python:3.11
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 80

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV DATABASE_URL=mongodb+srv://admin:admin@sessionary.pvqwstt.mongodb.net/

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
